catalog/urls.py
from django.urls import path

from catalog.views import index,\
    LiteraryFormatListView,\
    BookListView, BookDetailView,\
    LiteraryFormatCreateView,\
    LiteraryFormatUpdateView,\
    LiteraryFormatDeleteView, AuthorCreateView, AuthorListView, BookCreateView, BookUpdateView

urlpatterns = [
    path("", index, name="index"),
    path("literary-formats/", LiteraryFormatListView.as_view(), name="literary-formats-list"),
    path("literary-formats/create/", LiteraryFormatCreateView.as_view(), name="literary-formats-create"),
    path("literary-formats/<int:pk>/update/", LiteraryFormatUpdateView.as_view(), name="literary-formats-update"),
    path("literary-formats/<int:pk>/delete/", LiteraryFormatDeleteView.as_view(), name="literary-formats-delete"),
    path("books/", BookListView.as_view(), name="book-list"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("books/create/", BookCreateView.as_view(), name="book-create"),
    path("books/<int:pk>/update/", BookUpdateView.as_view(), name="book-update"),
    path("authors/", AuthorListView.as_view(), name="author-list"),
    path("authors/create/", AuthorCreateView.as_view(), name="author-create"),
]

app_name = "catalog"

library/urls.py
from django.contrib import admin
from django.urls import path, include
from catalog.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hello-world/", index),
    path("hello-world/<int:uniq_number>/", index),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from django.conf import settings


class LiteraryFormat(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Author(AbstractUser):
    pseudonym = models.CharField(max_length=63, null=True, blank=True)

    class Meta:
        ordering = ['username']
    # first_name = models.CharField(max_length=255)
    # last_name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.username} {self.first_name} {self.last_name}"


class Book(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    format = models.ForeignKey(
        LiteraryFormat,
        on_delete=models.CASCADE,
        related_name="books"
    )
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="books")

    def __str__(self):
        return f"{self.title} (price: {self.price}, format: {self.format})"

    class Meta:
        ordering = ["title"]

catalog/forms.py
from django.contrib.auth.forms import UserCreationForm
from catalog.models import Author, Book
from django import forms
from django.contrib.auth import get_user_model


class AuthorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Author
        fields = UserCreationForm.Meta.fields + ("pseudonym",)


class BookForm(forms.ModelForm):

    authors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Book
        fields = "__all__"


class BookSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title..."})
    )

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import generic
from catalog.forms import AuthorCreationForm, BookForm, BookSearchForm
from catalog.models import Book, Author, LiteraryFormat


# Create your views here.

@login_required
def index(request, uniq_number: int = 1):
    num_books = Book.objects.count()
    num_literary_formats = LiteraryFormat.objects.count()
    num_authors = Author.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_books": num_books,
        "num_authors": num_authors,
        "num_literary_formats": num_literary_formats,
        "num_visits": num_visits
    }
    return render(request, "catalog/index.html", context=context)


class LiteraryFormatListView(LoginRequiredMixin, generic.ListView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_list.html"
    context_object_name = "literary_formats_list"


class LiteraryFormatCreateView(LoginRequiredMixin, generic.CreateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-formats-list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-formats-list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatDeleteView(generic.DeleteView):
    model = LiteraryFormat
    context_object_name = "format_delete"
    success_url = reverse_lazy("catalog:literary-formats-list")
    template_name = "catalog/literary_format_confirm_delete.html"


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    template_name = "catalog/book_list.html"
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context["search_form"] = BookSearchForm()

        return context

    def get_queryset(self):
        queryset = Book.objects.select_related("format")
        title = self.request.GET.get("title")

        if title:
            return queryset.filter(title__icontains=title)
        return queryset


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class BookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Book
    form_class = BookForm
    template_name = "catalog/book_form.html"
    success_url = reverse_lazy("catalog:book-list")


class BookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Book
    success_url = reverse_lazy("catalog:book-list")
    template_name = "catalog/book_form.html"
    form_class = BookForm


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    paginate_by = 2
    template_name = "catalog/author_list.html"


class AuthorCreateView(LoginRequiredMixin, generic.CreateView):
    success_url = reverse_lazy("catalog:author-list")
    form_class = AuthorCreationForm
    template_name = "catalog/author_form.html"

# def book_detail_view(request, pk):
#     book = Book.objects.get(pk=pk)
#     context = {
#         "book": book,
#     }
#
#     return render(request, "catalog/book_detail.html", context=context)

# def literary_formats_list_view(request):
#     literary_formats = LiteraryFormat.objects.all()
#     context = {
#         "literary_formats": literary_formats
#     }
#     return render(request, "catalog/literary_format_list.html", context=context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Library</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-9">
      {% block content %}
      {% endblock %}
    {% block pagination %}
      {% include "includes/pagination.html" %}
    {% endblock %}
    </div>
  </div>
</div>
</body>
</html>

templates/catalog/author_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h4>
    Create Author
  </h4>
  <form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/author_list.html
{% extends "base.html" %}

P{% block content %}
  {% if author_list %}
    <ul>
    {% for author in author_list %}
      <li>Author username: {{ author.username }}({{ author.first_name }} {{ author.last_name }})</li>
    {% endfor %}
    </ul>
  {% else %}
    <p>There is no authors</p>
  {% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h4>Title: {{ book.title }}</h4>
  <p>Price: {{ book.price }}</p>
  <p>Format: {{ book.format }}</p>
  <hr>
  <p><a href="{% url 'catalog:book-update' pk=book.id %}">Update</a> book</p>
  <h4>Authors:</h4>
  {% for author in book.authors.all %}
    <li>Id: {{ author.id }}<br>
    Name: {{ author.first_name }} {{ author.last_name }}<br>
    {% if author.pseudonym %}(Pseudonym: {{ author.pseudonym }}){% endif %}
    </li>
  {% endfor %}
{% endblock %}

templates/catalog/book_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h4>
    {{ object|yesno:"Update,Create" }} Book
  </h4>
  <form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/book_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form action="" method="get" class="form-inline">
  {{ search_form|crispy }}
  <input class="btn btn-secondary" type="submit" value="🔎">
  </form>
  <a href="{% url 'catalog:book-create' %}">Create Book</a>
  {% if book_list %}
    <ul>
    {% for book in book_list %}
    <li><a href="{% url 'catalog:book-detail' pk=book.id %}">{{ book.title }}</a>(price: {{ book.price }}, format: {{ book.format }}</li>
    {% endfor %}
    </ul>
  {% else %}
    <p>There are no books</p>
  {% endif %}

{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}
{% block content %}
  <h3>Library Home</h3>
  <p>Welcome to the greates library!</p>
  <h5>Library Content:</h5>
  <ul>
    <li>num books: {{ num_books }}</li>
    <li>num authors: {{ num_authors }}</li>
    <li>num literary formats: {{ num_literary_formats }}</li>
    <li>num visits: {{ num_visits }}</li>
  </ul>
{% endblock %}

templates/catalog/literary_format_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form action="" method="post">
  {% csrf_token %}
  <p>Ypu wont to delete {{ format_delete }}></p>
  <input type="submit" value="Yes, delete!" class="btn-danger btn">
  </form>
{% endblock %}

templates/catalog/literary_format_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h4>
    {{ object|yesno:"Update,Create" }} Literary Format
  </h4>
  <form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/literary_format_list.html
{% extends "base.html" %}

{% block content %}
  <h4>Literary Format List
    <a href="{% url 'catalog:literary-formats-create' %}" style="float: right">+</a></h4>
  {% if literary_formats_list %}
    <table class="table">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for literary_format in literary_formats_list %}
    <tr>
      <td>
        {{ literary_format.id }}
      </td>
      <td>
        {{ literary_format.name }}
      </td>
      <td>
        <a href="{% url 'catalog:literary-formats-update' pk=literary_format.id%}">Update</a>
      </td>
      <td>
        <a href="{% url 'catalog:literary-formats-delete' pk=literary_format.id%}">Delete</a>
      </td>
    </tr>
    {% endfor %}
    </table>
  {% else %}
    <p>There are no literary formats</p>
  {% endif %}
{% endblock %}

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
    <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
      <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
      <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
    </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">
  {% if user.is_authenticated %}
    <li>User: {{ user.username }}</li>
    <li><a href="{% url 'logout' %}">Logout</a> </li>
  {% else %}
    <li><a href="{% url 'login' %}">Login</a> </li>
  {% endif %}
  <li><a href="{% url 'catalog:index' %}">Home</a></li>
  <li><a href="{% url 'catalog:author-list' %}">All authors</a></li>
  <li><a href="{% url 'catalog:book-list' %}">All books</a></li>
  <li><a href="{% url 'catalog:literary-formats-list' %}">All Formats</a></li>
</ul>